name: Go

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ main ]

env:
  CDT_VAULT_SECRET: very_secret

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [amd64]
        cgo: [0]
        os: [macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: macos-latest
            arch: arm64
            cgo: 1
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      env:
        GOARCH: ${{matrix.arch}}
        CGO_ENABLED: ${{matrix.cgo}}
      run: go build -o cdt -ldflags='-X main.version=dev -X main.binaryName=cdt'

    - name: Test
      run: go test -v ./...
