name: Go

on:
  push:
    branches: [ '*' ]
    tags: [ '*.*.*', 'v*.*.*', 'test-release-*' ]
  pull_request:
    branches: [ main ]

env:
  CDT_VAULT_SECRET: very_secret

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [amd64]
        cgo: [0]
        os: [macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: macos-latest
            arch: arm64
            cgo: 1
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: generate short sha1
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build
      env:
        GOARCH: ${{matrix.arch}}
        CGO_ENABLED: ${{matrix.cgo}}
      run: go build -o build/cdt_${{matrix.os}}_${{matrix.arch}}_${{github.ref_name}}-${{steps.vars.outputs.sha_short}} -ldflags='-X main.version=${{github.ref_name}}-${{steps.vars.outputs.sha_short}} -X main.binaryName=cdt'

    - name: Test
      run: go test -v ./...

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with: 
        files: build/cdt_${{matrix.os}}_${{matrix.arch}}_${{github.ref_name}}-${{steps.vars.outputs.sha_short}}
