name: Go

on:
  push:
    branches: [ '*' ]
    tags: [ '*.*.*', '*.*.*-*', 'test-release-*' ]
  pull_request:
    branches: [ main ]

env:
  CDT_VAULT_SECRET: very_secret

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [amd64]
        cgo: [0]
        os: [macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: macos-latest
            arch: arm64
            cgo: 1
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: generate short sha1
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=arch::${{matrix.arch}}"
        echo "::set-output name=os::$(go run test/get-os.go)"

    - name: Build
      env:
        GOARCH: ${{matrix.arch}}
        CGO_ENABLED: ${{matrix.cgo}}
      run: go build -o build/cdt_${{steps.vars.outputs.os}}_${{matrix.arch}}_${{github.ref_name}}-${{steps.vars.outputs.sha_short}} -ldflags='-X main.version=${{github.ref_name}} -X main.buildNum=${{github.run_attempt}} -X main.binaryName=cdt'

    - name: Test
      run: go test -v ./...

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.os}}-${{matrix.arch}}
        path: ${{github.workspace}}/command-launcher/build/cdt_${{steps.vars.outputs.os}}_${{matrix.arch}}_${{github.ref_name}}-${{steps.vars.outputs.sha_short}}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with: 
        files: build/cdt_${{matrix.os}}_${{matrix.arch}}_${{github.ref_name}}-${{steps.vars.outputs.sha_short}}

  packaging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download linux amd64 artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-amd64
          path: output/linux/amd64/
      - name: download windows amd64 artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-amd64
          path: output/windows/amd64/
      - name: download darwin amd64 artifact
        uses: actions/download-artifact@v3
        with:
          name: darwin-amd64
          path: output/darwin/amd64/
      - name: download darwin-arm64 artifact
        uses: actions/download-artifact@v3
        with:
          name: darwin-arm64
          path: output/darwin/arm64/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: output


